name: CI

on:
  push:
    branches:
    - master
  pull_request: []

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build and check
      run: ./gradlew check
    - name: Archive test report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports/tests/test
    - name: Archive JaCoCo report
      uses: actions/upload-artifact@v1
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html
